print("Введите коэффициенты A1, B1, C1, A2, B2, C2")
a1=int(input())
b1=int(input())
c1=int(input())
a2=int(input())
b2=int(input())
c2=int(input())
x=(c2-(b2*c1))/((b1*a2)-a1)
y=(c1-(a1*x))/b1
print("x=", x, "y=", y)
